units:
  # Proxy Keycap Spacing
  kx: cx
  ky: cy
  # Padded Keycap Spacing
  px: cx + 2 # 21 width
  py: cy + 2 # 20 height on flat 2d
points:
  zones:
    main:
      anchor: # to show PCB in KiCad
        shift: [100, 100]
      key:
        padding: ky # vertical
        spread: kx # horizontal
        width: kx # for preview
        height: ky # for preview
      columns:
        outer:
          key.column_net: P14
          rows:
            mod.skip: true
            bottom.key:
              led_prev: LED_25
              led_next: LED_26
            home.key:
              led_prev: LED_26
              led_next: LED_27
            top.key:
              led_prev: LED_27
              led_next: LED_28
            num.key: # Last key goes nowhere I guess
              led_prev: LED_28
              led_next: LED_29
        pinky:
          key.column_net: P16
          rows:
            mod.skip: true
            num.key:
              led_prev: LED_21
              led_next: LED_22
            top.key:
              led_prev: LED_22
              led_next: LED_23
            home.key:
              led_prev: LED_23
              led_next: LED_24
            bottom.key:
              led_prev: LED_24
              led_next: LED_25
        ring:
          key.stagger: 4.9
          key.column_net: P10
          rows:
            mod.column_net: P16
            mod.key:
              led_prev: LED_16
              led_next: LED_17
            bottom.key:
              led_prev: LED_17
              led_next: LED_18
            home.key:
              led_prev: LED_18
              led_next: LED_19
            top.key:
              led_prev: LED_19
              led_next: LED_20
            num.key:
              led_prev: LED_20
              led_next: LED_21
        middle:
          key.stagger: 2.5
          key.column_net: P7
          rows:
            mod.column_net: P10
            num.key:
              led_prev: LED_11
              led_next: LED_12
            top.key:
              led_prev: LED_12
              led_next: LED_13
            home.key:
              led_prev: LED_13
              led_next: LED_14
            bottom.key:
              led_prev: LED_14
              led_next: LED_15
            mod.key:
              led_prev: LED_15
              led_next: LED_16
        index:
          key.stagger: -2.5
          key.column_net: P8
          rows:
            mod.column_net: P7
            mod.key:
              led_prev: LED_6
              led_next: LED_7
            bottom.key:
              led_prev: LED_7
              led_next: LED_8
            home.key:
              led_prev: LED_8
              led_next: LED_9
            top.key:
              led_prev: LED_9
              led_next: LED_10
            num.key:
              led_prev: LED_10
              led_next: LED_11
        inner:
          key.stagger: -2.5
          key.column_net: P9
          rows:
            mod.skip: true
            num.key:
              led_prev: P0
              led_next: LED_1
            top.key:
              led_prev: LED_1
              led_next: LED_2
            home.key:
              led_prev: LED_2
              led_next: LED_3
            bottom.key:
              led_prev: LED_3
              led_next: LED_4
      rows:
        mod:
          row_net: P15
        bottom:
          row_net: P18
        home:
          row_net: P19
        top:
          row_net: P20
        num:
          row_net: P21
    thumbs:
      key:
        padding: ky
        spread: kx
        width: kx
        height: ky
      anchor:
        ref: main_inner_mod
        shift: [2.5, -2.5]
      columns:
        layer:
          key.splay: -15
          key.column_net: P8
          rows:
            cluster.key:
              led_prev: LED_5
              led_next: LED_6
        space: # TODO: tut uses 75 splay with neg y shift, no rotate
          key.splay: -15
          key.shift: [2.5, 3]
          key.width: 1.5kx
          key.rotate: -90
          key.column_net: P9
          rows:
            cluster.key:
              led_prev: LED_4
              led_next: LED_5
      rows:
        cluster:
          row_net: P15
outlines:
  outline: # idk tbh
    - what: rectangle
      where: true
      size: [px, py]
  keys: # key overlaps
    - what: rectangle
      where: true
      size: [kx-0.1, ky-0.1]
  board: # PCB Board outline
    - what: polygon
      operation: stack
      points:
        - ref: main_outer_num
          shift: [-0.5px, 0.5py]
        - ref: main_middle_num
          shift: [-0.5px, 0.6py]
        - ref: main_inner_num
          shift: [1.5px, 0.625py]
        - ref: main_inner_bottom
          shift: [1.5px, -0.25py]
        - ref: thumbs_space_cluster
          shift: [-0.5px, 0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px, 0.5py]
        - ref: main_index_mod
          shift: [0, -0.5py]
        - ref: main_ring_mod
          shift: [-0.5px, -0.5py]
        - ref: main_outer_bottom
          shift: [-0.5px, -0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  main_pcb:
    outlines:
      main:
        outline:
          board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      rgb:
        what: sk6812mini-e
        where: true
        adjust:
          shift: [0, 4.5]
        params:
          P2: "{{key.led_next}}"
          P4: "{{key.led_prev}}"
      diode:
        what: combo-diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
          # reversible: true
        adjust:
          shift: [7.5, 0]
          rotate: 90
      promicro:
        what: promicro
        where:
          ref: main_inner_num
          shift: [1kx+1, -8]
          rotate: -90
      oled:
        what: oled
        params:
          SDA: P2 # I2C SDA
          SCL: P3 # I2C SCL
        where:
          ref: main_inner_num
          shift: [1kx-5, -27]
          rotate: 90
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: main_inner_num
          shift: [1kx + 1, -31]
      trrs:
        what: trrs
        params:
          A: P1 # UART0 Serial TX Top left on back
          B: VCC
          C: GND
          D: P0 # UART0 Serial RX Top left, under P1 (yes P0 is under P1)
        where:
          ref: main_inner_num
          shift: [1kx + 9, -42]
          rotate: -90
