units:
  # Proxy Keycap Spacing
  kx: cx
  ky: cy
  # Padded Keycap Spacing
  px: cx + 2 # 21 width
  py: cy + 2 # 20 height on flat 2d
points:
  zones:
    main:
      anchor: # to show PCB in KiCad
        shift: [150, -200]
      key:
        padding: ky # vertical
        spread: kx # horizontal
        width: kx # for preview
        height: ky # for preview
      columns:
        outer:
          key.column_net: P22
          rows:
            mod.skip: true
            bottom.key:
              led_prev: LED_25
              led_next: LED_26
            home.key:
              led_prev: LED_26
              led_next: LED_27
            top.key:
              led_prev: LED_27
              led_next: LED_28
            num.key: # Last key goes nowhere I guess
              led_prev: LED_28
              led_next: LED_29
        pinky:
          key.column_net: P26
          rows:
            mod.skip: true
            num.key:
              led_prev: LED_21
              led_next: LED_22
            top.key:
              led_prev: LED_22
              led_next: LED_23
            home.key:
              led_prev: LED_23
              led_next: LED_24
            bottom.key:
              led_prev: LED_24
              led_next: LED_25
        ring:
          key.stagger: 4.9
          key.column_net: P27
          rows:
            mod.column_net: P26
            mod.key:
              led_prev: LED_16
              led_next: LED_17
            bottom.key:
              led_prev: LED_17
              led_next: LED_18
            home.key:
              led_prev: LED_18
              led_next: LED_19
            top.key:
              led_prev: LED_19
              led_next: LED_20
            num.key:
              led_prev: LED_20
              led_next: LED_21
        middle:
          key.stagger: 2.5
          key.column_net: P28
          rows:
            mod.column_net: P27
            num.key:
              led_prev: LED_11
              led_next: LED_12
            top.key:
              led_prev: LED_12
              led_next: LED_13
            home.key:
              led_prev: LED_13
              led_next: LED_14
            bottom.key:
              led_prev: LED_14
              led_next: LED_15
            mod.key:
              led_prev: LED_15
              led_next: LED_16
        index:
          key.stagger: -2.5
          key.column_net: P29
          rows:
            mod.column_net: P28
            mod.key:
              led_prev: LED_6
              led_next: LED_7
            bottom.key:
              led_prev: LED_7
              led_next: LED_8
            home.key:
              led_prev: LED_8
              led_next: LED_9
            top.key:
              led_prev: LED_9
              led_next: LED_10
            num.key:
              led_prev: LED_10
              led_next: LED_11
        inner:
          key.stagger: -2.5
          key.column_net: P11
          rows:
            mod.skip: true
            num.key:
              led_prev: P7 # This pin connects to the MCU for LED signal
              led_next: LED_1
            top.key:
              led_prev: LED_1
              led_next: LED_2
            home.key:
              led_prev: LED_2
              led_next: LED_3
            bottom.key:
              led_prev: LED_3
              led_next: LED_4
      rows:
        mod:
          row_net: P6
        bottom:
          row_net: P5
        home:
          row_net: P4
        top:
          row_net: P3
        num:
          row_net: P2
    thumbs:
      key:
        padding: ky
        spread: kx
        width: kx
        height: ky
      anchor:
        ref: main_inner_mod
        shift: [2.5, -2.5]
      columns:
        layer:
          key.splay: -15
          key.column_net: P29
          rows:
            cluster.key:
              led_prev: LED_5
              led_next: LED_6
        space: # TODO: tut uses 75 splay with neg y shift, no rotate
          key.splay: -15
          key.shift: [2.5, 3]
          key.width: 1.5kx
          key.rotate: -90
          key.column_net: P11
          rows:
            cluster.key:
              led_prev: LED_4
              led_next: LED_5
      rows:
        cluster:
          row_net: P6
outlines:
  outline: # idk tbh
    - what: rectangle
      where: true
      size: [px, py]
  keys: # key overlaps
    - what: rectangle
      where: true
      size: [kx-0.1, ky-0.1]
  board: # PCB Board outline
    - what: polygon
      operation: stack
      points:
        - ref: main_outer_num
          shift: [-0.5px, 0.5py]
        - ref: main_middle_num
          shift: [-0.5px, 0.6py]
        - ref: main_inner_num
          shift: [1.5px, 0.625py]
        - ref: main_inner_bottom
          shift: [1.5px, -0.25py]
        - ref: thumbs_space_cluster
          shift: [-0.5px, 0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px, 0.5py]
        - ref: main_index_mod
          shift: [0, -0.5py]
        - ref: main_ring_mod
          shift: [-0.5px, -0.5py]
        - ref: main_outer_bottom
          shift: [-0.5px, -0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  main_pcb:
    outlines:
      main:
        outline:
          board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          # reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      # rgb:
      #   what: sk6812mini-e
      #   where: true
      #   adjust:
      #     shift: [0, 4.5]
      #   params:
      #     # reversible: true
      #     reverse_mount: true
      #     P2: "{{key.led_next}}"
      #     P4: "{{key.led_prev}}"
      diode:
        what: combo-diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: true
          # reversible: true
        adjust:
          shift: [-7.8, 3.8]
          rotate: -90
      # promicro: # TODO - Wire up after putting in ProMicroAX
      #   what: promicro
      #   where:
      #     ref: main_inner_num
      #     shift: [1kx+1, -8]
      #     rotate: -90
      promicro2: # TODO - Wire up after putting in ProMicroAX
        what: promicro-ax
        where:
          ref: main_inner_num
          shift: [1kx, -8]
          rotate: -90
      # promicro2-back: # TODO - Wire up after putting in ProMicroAX
      #   what: promicro-ax
      #   where:
      #     ref: main_inner_num
      #     shift: [1kx+1.68, -6.73] # -8 + 2.54/2
      #     rotate: -90
      #   params:
      #     side: 'B'
      # oled: # TODO: Wire these up after putting in ProMicroAX
      #   what: combo-display
      #   params:
      #     oled: 'ssd1306'
      #     reversible: true
      #     P1: VDD
      #     P4: P20 # I2C SDA  TODO: Check this matches up with OLED!!
      #     P3: P21 # I2C SCL
      #   where:
      #     ref: main_inner_num
      #     shift: [1kx+1, -25]
      # reset: ## TODO - is this needed?
      #   what: button
      #   params:
      #     from: GND
      #     to: RST
      #   where:
      #     ref: main_inner_num
      #     shift: [1kx + 1, -31]
      trrs: # TODO: Wire these up after putting in ProMicroAX
        what: trrs
        params:
          # reverse: true
          # symmetric: true
          A: P8 # Note - only supports Serial, not I2C
          B: GND
          C: VDD # UART1 TX bottom left
          D: VDD
        where:
          ref: main_inner_num
          shift: [1kx + 9, -42]
          rotate: -90
